server:
  port: ${PORT:8085}

spring:
  application:
    name: notification-service

  # canonical single redis URL (prefer this)
  data:
    redis: # ✅ Correct prefix for Spring Boot 3.x+
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}
      password: ${SPRING_REDIS_PASSWORD:}
      ssl:
        enabled: ${SPRING_REDIS_SSL_ENABLED:true}

  # Optional: fallback for older libraries using spring.redis.*
  redis:
    url: ${REDIS_URL:}

# ---------- EUREKA ----------
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URL:https://eureka-server-sk4j.onrender.com/eureka/}
  instance:
    prefer-ip-address: true
    hostname: ${spring.application.name}
    instance-id: ${spring.application.name}:${random.value}
    metadata-map:
      management.port: ${server.port}

jwt:
  secret: ${JWT_SECRET_KEY:supreme-solutions-secret-key-9876543210@#jwt}
