server:
  port: ${PORT:8085}

spring:
  application:
    name: notification-service

    redis:
      host: ${SPRING_REDIS_HOST}
      port: ${SPRING_REDIS_PORT}
      password: ${SPRING_REDIS_PASSWORD}
      ssl:
        enabled: ${SPRING_REDIS_SSL_ENABLED:true}
      timeout: 3000ms

# ---------- EUREKA ----------
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URL:https://eureka-server-sk4j.onrender.com/eureka/}
  instance:
    prefer-ip-address: true
    hostname: ${spring.application.name}
    instance-id: ${spring.application.name}:${random.value}
    metadata-map:
      management.port: ${server.port}

jwt:
  secret: ${JWT_SECRET_KEY:supreme-solutions-secret-key-9876543210@#jwt}
